apiVersion: v1
kind: Service
metadata:
  namespace: miro-infra
  name: faas-gateway
  labels:
    app: faas-gateway
spec:
  type: LoadBalancer
  selector:
    app: faas-gateway
  ports:
  - name: http
    port: 8080
    targetPort: http